name: Build and Test k-NN
on:
  schedule:
    - cron: '0 0 * * *'  # every night
  push:
    branches:
      - "*"
      - "feature/**"
  pull_request:
    branches:
      - "*"
      - "feature/**"

jobs:
  Get-CI-Image-Tag:
    uses: opensearch-project/opensearch-build/.github/workflows/get-ci-image-tag.yml@main
    with:
      product: opensearch

  Build-k-NN-MacOS:
    strategy:
      matrix:
        java: [ 11 ]

    name: Build and Test k-NN Plugin on MacOS
    needs: Get-CI-Image-Tag
    runs-on: macos-13

    steps:
      - name: Checkout k-NN
        uses: actions/checkout@v1

      - name: Check system capabilities
        run: |
          # use arch to check the system architecture
          arch

      # Setup git user so that patches for native libraries can be applied and committed
      - name: Setup git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Install dependencies on macos
        run: |
          brew reinstall gcc
          brew reinstall llvm
          export FC=/usr/local/Cellar/gcc/12.2.0/bin/gfortran

      - name: Run build
        run: |
          if sysctl -n machdep.cpu.features machdep.cpu.leaf7_features | grep -i AVX2
          then
#              echo "avx2 available on system"
#              cd jni
#              cmake . --fresh
#              make
              ./gradlew build
          else
#              echo "avx2 not available on system"
#              cd jni
#              cmake . --fresh -DOpenMP_CXX_INCLUDE_DIR=/usr/local/opt/llvm/include/openmp -DSIMD_ENABLED=false
#              make
              ./gradlew build -Dsimd.enabled=false
          fi
